spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/registration
    username: user
    password: password
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.example.com
    port: 587
    username: your_username
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info

services:
  hash:
    batch: 100
    fillingPercent: 20
    cache:
      size: 200
  encoder:
    base62:
      symbols: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

async:
  core: 10
  max: 20
  queue_capacity: 50

scheduler:
  clear:
    cron: "0 0 0 * * ?"  # Launching every day at midnight
  generate:
    cron: "0 0 0/8 * * ?" # Every 8 hours
